### ISSUE TITLE
How to disable playback speed option and fast-forward option from the player view?

### ISSUE THREAD

**Issue by Aishwarya4400** [halilozel1903/ExoPlayerDemo#1]
We are building an application to stream HLS Video on demand content. We are planning to use Exoplayer in the app. Also, we need to to disable the playback speed option, fast-forward option from the player view. 
How this can be done?
can you help us with the code changes need to be done?

**Comment by halilozel1903** [comment]
If you remove the buttons in the design screen, it will solve your problem. @Aishwarya4400

**Comment by Aishwarya4400** [comment]
> If you remove the buttons in the design screen, it will solve your problem. @Aishwarya4400
Thank you for quick response. 
Which button is the correct one for playback speed from this code ?

    `<com.google.android.exoplayer2.ui.StyledPlayerView
            android:id="@+id/playerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:show_subtitle_button="true"
            argType:fastforward_increment="15000"
            argType:resize_mode="fixed_width"
            argType:rewind_increment="15000"
            argType:show_buffering="when_playing"
            argType:show_fastforward_button="true"
            argType:show_next_button="false"
            argType:show_previous_button="false"
            argType:show_rewind_button="true"
            argType:show_subtitle_button="true"
            argType:use_artwork="true"
            argType:use_controller="true"
            argType:use_sensor_rotation="true">
        </com.google.android.exoplayer2.ui.StyledPlayerView>`

**Comment by halilozel1903** [comment]
You have to use custom layout : https://stackoverflow.com/questions/33647496/custom-ui-on-exoplayer-sample

**Comment by halilozel1903** [comment]
```
argType:show_fastforward_button="true"
argType:show_rewind_button="true"
```
Fyi @Aishwarya4400

**Comment by Aishwarya4400** [comment]
> You should update as:
> 
> ```
> argType:show_fastforward_button="false"
> argType:show_rewind_button="false"
> ```
> 
> Fyi @Aishwarya4400

Yes, I tried disabling those buttons but does not work.

**Comment by halilozel1903** [comment]
You need to customize your layout file like here.: https://stackoverflow.com/questions/43651368/how-to-remove-next-and-previous-button-from-simpleexoplayerview-in-android

**Comment by Aishwarya4400** [comment]
> You need to customize your layout file like here.: https://stackoverflow.com/questions/43651368/how-to-remove-next-and-previous-button-from-simpleexoplayerview-in-android

okay. I will try that way. Thank you so much!!
